#!/bin/bash
#
# setup-haproxy.sh - Install and configure HAProxy on the VPS to forward
# :80 and :443 to a WireGuard peer, prepending PROXY Protocol v2 so the
# homelab sees the real client IP.
#
# Usage:  ./setup-haproxy.sh <wireguard_client_ip> [client_http_port] [client_https_port]
# Example: ./setup-haproxy.sh 10.8.0.2
#
set -e

if [[ $EUID -ne 0 ]]; then
  echo "Error: This script must be run as root"
  exit 1
fi

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <wireguard_client_ip> [client_http_port] [client_https_port]"
  exit 1
fi

CLIENT_IP="$1"
HTTP_PORT="${2:-80}"
HTTPS_PORT="${3:-443}"

if ! [[ "$CLIENT_IP" =~ ^[0-9.]+$ ]]; then
  echo "Error: invalid client IP '$CLIENT_IP'"
  exit 1
fi
if ! [[ "$HTTP_PORT" =~ ^[0-9]+$ ]] || ! [[ "$HTTPS_PORT" =~ ^[0-9]+$ ]]; then
  echo "Error: invalid port(s)"
  exit 1
fi

# Refuse to start if something is already bound to :80 or :443 (e.g. nginx).
check_port() {
  if ss -ltn "sport = :$1" 2>/dev/null | grep -q ":$1 "; then
    echo "Error: port $1 is already in use. Stop the service using it first."
    exit 1
  fi
}
command -v ss >/dev/null 2>&1 || apt install -y iproute2
check_port "$HTTP_PORT"
check_port "$HTTPS_PORT"

echo "Installing HAProxy..."
apt update
apt install -y haproxy

CONF="/etc/haproxy/haproxy.cfg"

echo "Writing $CONF (forward :${HTTP_PORT}/:${HTTPS_PORT} -> ${CLIENT_IP} with PROXY Protocol v2)..."

# Back up any existing config exactly once.
if [[ -f "$CONF" && ! -f "${CONF}.orig" ]]; then
  cp "$CONF" "${CONF}.orig"
fi

cat > "$CONF" << EOF
# Generated by setup-haproxy.sh
# Forwards raw TCP :80/:443 to the WireGuard peer, injecting PROXY Protocol v2
# so the homelab Caddy can recover the real client IP.

global
    log /dev/log local0
    maxconn 4096
    # Run under systemd master-worker; do NOT daemonize here.
    stats socket /run/haproxy/admin.sock mode 660 level admin
    user haproxy
    group haproxy

defaults
    log     global
    mode    tcp
    option  tcplog
    timeout connect 5s
    timeout client  50s
    timeout server  50s

frontend http_in
    bind *:${HTTP_PORT}
    default_backend homelab_http

frontend https_in
    bind *:${HTTPS_PORT}
    default_backend homelab_https

backend homelab_http
    option tcp-check
    server homelab ${CLIENT_IP}:${HTTP_PORT} check send-proxy-v2

backend homelab_https
    option tcp-check
    server homelab ${CLIENT_IP}:${HTTPS_PORT} check send-proxy-v2
EOF

echo "Validating HAProxy config..."
haproxy -c -f "$CONF"

echo "Enabling and (re)starting HAProxy..."
systemctl enable haproxy
systemctl restart haproxy

echo ""
echo "HAProxy setup complete."
echo "  Frontend  : ${HTTP_PORT} (http), ${HTTPS_PORT} (https)"
echo "  Backend   : ${CLIENT_IP}:${HTTP_PORT}, ${CLIENT_IP}:${HTTPS_PORT}"
echo "  PROXY Protocol: v2 (send-proxy-v2)"
echo "  Config    : $CONF  (original saved as ${CONF}.orig)"
echo ""
echo "Next: configure your homelab Caddy to accept PROXY Protocol"
echo "      (see setup-homelab-waf.sh) and to set trusted client IP"
echo "      via the proxy_protocol listener wrapper."