---
- name: Add CrowdSec GPG key
  ansible.builtin.get_url:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    dest: /etc/apt/keyrings/crowdsec.asc
    mode: "0644"

- name: Add CrowdSec apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/crowdsec.asc] https://packagecloud.io/crowdsec/crowdsec/ubuntu/ jammy main"
    filename: crowdsec
    state: present

- name: Install CrowdSec firewall bouncer
  ansible.builtin.apt:
    name: crowdsec-firewall-bouncer-nftables
    state: present
    update_cache: true

- name: Configure CrowdSec firewall bouncer
  ansible.builtin.template:
    src: crowdsec-firewall-bouncer.yaml.j2
    dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
    mode: "0600"
    owner: root
    group: root
  no_log: true
  notify: Restart crowdsec-firewall-bouncer

- name: Enable and start CrowdSec firewall bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    enabled: true
    state: started
    daemon_reload: true
